import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ayush',
      email: 'ayush@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Boat Rockerz',
      slug: 'boat',
      category: 'Music',
      image: '/images/boat450.jpg',
      price: 650,
      countInStock: 15,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Sony headset',
      slug: 'sony',
      category: 'Music',
      image: '/images/sony.jpg',
      price: 1000,
      countInStock: 2,
      brand: 'Sony',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '7',
      name: 'Saregama',
      slug: 'saregama',
      category: 'Music',
      image: '/images/saregama.jpg',
      price: 5000,
      countInStock: 5,
      brand: 'Saregama',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Garmin',
      slug: 'garmin',
      category: 'Watches',
      image: '/images/garmin.jpg',
      price: 1500,
      countInStock: 12,
      brand: 'garmin',
      rating: 3.8,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
};
export default data;
